name: Run Leumi Bot
on:
  schedule:
    # 0-4 מייצג את ימי ראשון עד חמישי (ימי המסחר בישראל)
    - cron: '30 13 * * 0-4' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install yfinance pyTelegramBotAPI requests

      - name: Run bot
        # כאן אנחנו "מזריקים" את הסודות מהכספת לתוך הזיכרון של השרת
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python "TEST BANKS.py"
